development:
  connection:
    domain: "development.visabusinessnetwork.com"
    hosts:
      - 72.2.120.107:7001
      - 8.17.84.194:7001
  class: "file"

staging:
  connection:
    domain: "staging.visabusinessnetwork.com"
    hosts:
      - 72.2.120.107:7001
      - 8.17.84.194:7001
  class: "file"

production:
  connection:
    domain: "production.visabusinessnetwork.com"
    hosts:
      - 72.2.120.107:7001
      - 8.17.84.194:7001
  class: "file"
