# Example MogileFS configuration.

development:
  connection:
    domain: "development.someapplication.com"
    hosts:
      - 72.2.120.107:7001
  class: "file"

staging:
  connection:
    domain: "staging.someapplication.com"
    hosts:
      - 72.2.120.107:7001
  class: "file"

production:
  connection:
    domain: "production.someapplication.com"
    hosts:
      - 72.2.120.107:7001
  class: "file"
